"""JSON companion HTML reports without external template dependencies."""

from __future__ import annotations

import html
import json
from pathlib import Path
from typing import Any

from .io import write_json


def _render_value(value: Any) -> str:
    if isinstance(value, bool):
        return "PASS" if value else "FAIL"
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, indent=2)
    return str(value)


def write_report(json_path: Path, html_path: Path, title: str, report: dict[str, Any]) -> None:
    """Write the same report as machine-readable JSON and standalone HTML."""

    write_json(json_path, report)
    rows = []
    for key, value in report.items():
        rendered = html.escape(_render_value(value))
        rows.append(f"<tr><th>{html.escape(str(key))}</th><td><pre>{rendered}</pre></td></tr>")
    document = f"""<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>{html.escape(title)}</title>
<style>
body{{font:15px/1.55 system-ui,"Microsoft YaHei",sans-serif;max-width:1100px;margin:32px auto;padding:0 20px;color:#17202a}}
h1{{font-size:26px}}table{{border-collapse:collapse;width:100%}}th,td{{border:1px solid #ccd1d1;padding:10px;vertical-align:top;text-align:left}}
th{{width:220px;background:#f4f6f7}}pre{{white-space:pre-wrap;word-break:break-word;margin:0}}.meta{{color:#566573}}
</style>
</head>
<body><h1>{html.escape(title)}</h1><p class="meta">Generated by BidCrawler Factory.</p><table>{''.join(rows)}</table></body>
</html>
"""
    html_path.parent.mkdir(parents=True, exist_ok=True)
    html_path.write_text(document, encoding="utf-8")
