"""Generate a site development project without overwriting existing work."""

from __future__ import annotations

from pathlib import Path

from .errors import FactoryError
from .io import safe_filename, write_json


ADAPTER_TEMPLATE = '''"""Site adapter generated by BidCrawler Factory."""


def parse_fixture(bundle):
    """Convert recorded responses into normalized bid records.

    Replace the generic parser with site-specific list/detail joining when needed.
    """

    records = []
    for response in bundle:
        if response.body_path.suffix.lower() != ".json" and "json" not in response.content_type.lower():
            continue
        payload = response.json()
        candidates = payload.get("rows") or payload.get("records") or payload.get("items") or []
        if isinstance(candidates, list):
            records.extend(dict(item) for item in candidates if isinstance(item, dict))
    return records
'''


TEST_TEMPLATE = '''import json
from pathlib import Path

from adapter import parse_fixture
from bidfactory.fixture import load_bundle


def test_adapter_contract():
    fixture = Path(__file__).resolve().parents[1] / "fixtures" / "latest"
    if not (fixture / "manifest.json").exists():
        return
    manifest = json.loads((fixture / "manifest.json").read_text(encoding="utf-8"))
    if not (manifest.get("entries") or manifest.get("requests")):
        return
    records = parse_fixture(load_bundle(fixture))
    assert isinstance(records, list)
    assert all(isinstance(record, dict) for record in records)
'''


README_TEMPLATE = '''# {site_name}

本目录是站点开发工作区。内部可使用多文件结构，最终通过 `bidfactory package` 输出单文件客户交付包。

## 快速开始

```powershell
python -m bidfactory capture site_config.json --output fixtures/latest
python -m bidfactory replay fixtures/latest --adapter adapter.py --output artifacts/records.json
python -m bidfactory validate artifacts/records.json --output reports
python -m bidfactory package .
```

先补充 `site_config.json` 中的公开请求配置，再在 `adapter.py` 中实现站点字段映射。不要保存 Cookie、Token、密码或生产数据库配置。
'''


def new_site(site_name: str, root: Path, template_path: Path | None = None) -> Path:
    """Create an isolated site project and refuse to overwrite a target."""

    display_name = str(site_name).strip()
    if not display_name:
        raise FactoryError("Site name cannot be empty")
    slug = safe_filename(display_name)
    target = (root / slug).resolve()
    if target.exists():
        raise FactoryError(f"Site project already exists; refusing to overwrite: {target}")
    target.mkdir(parents=True)
    for name in ("src", "fixtures/latest/bodies", "artifacts", "reports", "tests", "docs"):
        (target / name).mkdir(parents=True, exist_ok=True)

    template = template_path or (Path(__file__).resolve().parents[1] / "templates" / "single_site_crawler_template.py")
    if not template.exists():
        raise FactoryError(f"Crawler template is missing: {template}")
    source_text = template.read_text(encoding="utf-8-sig")
    source_text = source_text.replace('SITE_KEY = "example_site"', f"SITE_KEY = {slug.lower()!r}")
    source_text = source_text.replace('WEBNAME = "示例招投标网站"', f"WEBNAME = {display_name!r}")
    (target / "src" / f"{slug}_爬虫.py").write_text(source_text, encoding="utf-8")
    (target / "adapter.py").write_text(ADAPTER_TEMPLATE, encoding="utf-8")
    (target / "tests" / "test_adapter.py").write_text(TEST_TEMPLATE, encoding="utf-8")
    (target / "README.md").write_text(README_TEMPLATE.format(site_name=display_name), encoding="utf-8")
    (target / "requirements.txt").write_text("requests>=2.31.0\npymysql>=1.1.0\n", encoding="utf-8")
    (target / ".gitignore").write_text(
        ".env\n__pycache__/\n.pytest_cache/\nreports/\nartifacts/\nfixtures/*\n!fixtures/latest/\n!fixtures/latest/manifest.json\n",
        encoding="utf-8",
    )
    write_json(
        target / "site_config.json",
        {
            "schema_version": 1,
            "site_name": display_name,
            "site_key": slug.lower(),
            "base_url": "https://example.com",
            "allowed_hosts": ["example.com"],
            "request_delay": 0.2,
            "max_response_bytes": 10_000_000,
            "adapter": "adapter.py",
            "expected_categories": [],
            "dom_selectors": {},
            "requests": [],
        },
    )
    write_json(
        target / "fixtures" / "latest" / "manifest.json",
        {
            "schema_version": 1,
            "site_name": display_name,
            "expected_categories": [],
            "dom_selectors": {},
            "requests": [],
        },
    )
    return target
